// source: slotsgames/slots_game.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var slotsgames_asymmetric_reels_slots_game_pb = require('../slotsgames/asymmetric_reels_slots_game_pb.js');
goog.object.extend(proto, slotsgames_asymmetric_reels_slots_game_pb);
var slotsgames_accumulate_multiplier_slots_game_pb = require('../slotsgames/accumulate_multiplier_slots_game_pb.js');
goog.object.extend(proto, slotsgames_accumulate_multiplier_slots_game_pb);
var slotsgames_scatter_prize_pb = require('../slotsgames/scatter_prize_pb.js');
goog.object.extend(proto, slotsgames_scatter_prize_pb);
goog.exportSymbol('proto.schema.PaylineModel', null, global);
goog.exportSymbol('proto.schema.PaylineSlotsGameModel', null, global);
goog.exportSymbol('proto.schema.PaylineSlotsGameModel.GameCase', null, global);
goog.exportSymbol('proto.schema.SlotsGameModel', null, global);
goog.exportSymbol('proto.schema.SlotsGameModel.GameCase', null, global);
goog.exportSymbol('proto.schema.SlotsGameSymbolModel', null, global);
goog.exportSymbol('proto.schema.SlotsGameSymbolModel.SymbolCase', null, global);
goog.exportSymbol('proto.schema.WaySlotsGameModel', null, global);
goog.exportSymbol('proto.schema.WaySlotsGameModel.GameCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schema.SlotsGameModel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.schema.SlotsGameModel.repeatedFields_, proto.schema.SlotsGameModel.oneofGroups_);
};
goog.inherits(proto.schema.SlotsGameModel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schema.SlotsGameModel.displayName = 'proto.schema.SlotsGameModel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schema.SlotsGameSymbolModel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.schema.SlotsGameSymbolModel.repeatedFields_, proto.schema.SlotsGameSymbolModel.oneofGroups_);
};
goog.inherits(proto.schema.SlotsGameSymbolModel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schema.SlotsGameSymbolModel.displayName = 'proto.schema.SlotsGameSymbolModel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schema.PaylineModel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.schema.PaylineModel.repeatedFields_, null);
};
goog.inherits(proto.schema.PaylineModel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schema.PaylineModel.displayName = 'proto.schema.PaylineModel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schema.PaylineSlotsGameModel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.schema.PaylineSlotsGameModel.repeatedFields_, proto.schema.PaylineSlotsGameModel.oneofGroups_);
};
goog.inherits(proto.schema.PaylineSlotsGameModel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schema.PaylineSlotsGameModel.displayName = 'proto.schema.PaylineSlotsGameModel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.schema.WaySlotsGameModel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.schema.WaySlotsGameModel.oneofGroups_);
};
goog.inherits(proto.schema.WaySlotsGameModel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.schema.WaySlotsGameModel.displayName = 'proto.schema.WaySlotsGameModel';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.schema.SlotsGameModel.repeatedFields_ = [1,2,3,4,5];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.schema.SlotsGameModel.oneofGroups_ = [[6,7]];

/**
 * @enum {number}
 */
proto.schema.SlotsGameModel.GameCase = {
  GAME_NOT_SET: 0,
  PAYLINE_SLOTS_GAME: 6,
  WAY_SLOTS_GAME: 7
};

/**
 * @return {proto.schema.SlotsGameModel.GameCase}
 */
proto.schema.SlotsGameModel.prototype.getGameCase = function() {
  return /** @type {proto.schema.SlotsGameModel.GameCase} */(jspb.Message.computeOneofCase(this, proto.schema.SlotsGameModel.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schema.SlotsGameModel.prototype.toObject = function(opt_includeInstance) {
  return proto.schema.SlotsGameModel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schema.SlotsGameModel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.SlotsGameModel.toObject = function(includeInstance, msg) {
  var f, obj = {
    slotsSymbolList: jspb.Message.toObjectList(msg.getSlotsSymbolList(),
    proto.schema.SlotsGameSymbolModel.toObject, includeInstance),
    goldCoinsBetValuesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f,
    sweepCoinsBetValuesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f,
    rowCountsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    scatterPrizesList: jspb.Message.toObjectList(msg.getScatterPrizesList(),
    slotsgames_scatter_prize_pb.ScatterPrizeModel.toObject, includeInstance),
    paylineSlotsGame: (f = msg.getPaylineSlotsGame()) && proto.schema.PaylineSlotsGameModel.toObject(includeInstance, f),
    waySlotsGame: (f = msg.getWaySlotsGame()) && proto.schema.WaySlotsGameModel.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schema.SlotsGameModel}
 */
proto.schema.SlotsGameModel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schema.SlotsGameModel;
  return proto.schema.SlotsGameModel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schema.SlotsGameModel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schema.SlotsGameModel}
 */
proto.schema.SlotsGameModel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.schema.SlotsGameSymbolModel;
      reader.readMessage(value,proto.schema.SlotsGameSymbolModel.deserializeBinaryFromReader);
      msg.addSlotsSymbol(value);
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addGoldCoinsBetValues(values[i]);
      }
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSweepCoinsBetValues(values[i]);
      }
      break;
    case 4:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRowCounts(values[i]);
      }
      break;
    case 5:
      var value = new slotsgames_scatter_prize_pb.ScatterPrizeModel;
      reader.readMessage(value,slotsgames_scatter_prize_pb.ScatterPrizeModel.deserializeBinaryFromReader);
      msg.addScatterPrizes(value);
      break;
    case 6:
      var value = new proto.schema.PaylineSlotsGameModel;
      reader.readMessage(value,proto.schema.PaylineSlotsGameModel.deserializeBinaryFromReader);
      msg.setPaylineSlotsGame(value);
      break;
    case 7:
      var value = new proto.schema.WaySlotsGameModel;
      reader.readMessage(value,proto.schema.WaySlotsGameModel.deserializeBinaryFromReader);
      msg.setWaySlotsGame(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schema.SlotsGameModel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schema.SlotsGameModel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schema.SlotsGameModel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.SlotsGameModel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSlotsSymbolList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.schema.SlotsGameSymbolModel.serializeBinaryToWriter
    );
  }
  f = message.getGoldCoinsBetValuesList();
  if (f.length > 0) {
    writer.writePackedDouble(
      2,
      f
    );
  }
  f = message.getSweepCoinsBetValuesList();
  if (f.length > 0) {
    writer.writePackedDouble(
      3,
      f
    );
  }
  f = message.getRowCountsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      4,
      f
    );
  }
  f = message.getScatterPrizesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      slotsgames_scatter_prize_pb.ScatterPrizeModel.serializeBinaryToWriter
    );
  }
  f = message.getPaylineSlotsGame();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.schema.PaylineSlotsGameModel.serializeBinaryToWriter
    );
  }
  f = message.getWaySlotsGame();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.schema.WaySlotsGameModel.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SlotsGameSymbolModel slots_symbol = 1;
 * @return {!Array<!proto.schema.SlotsGameSymbolModel>}
 */
proto.schema.SlotsGameModel.prototype.getSlotsSymbolList = function() {
  return /** @type{!Array<!proto.schema.SlotsGameSymbolModel>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.schema.SlotsGameSymbolModel, 1));
};


/**
 * @param {!Array<!proto.schema.SlotsGameSymbolModel>} value
 * @return {!proto.schema.SlotsGameModel} returns this
*/
proto.schema.SlotsGameModel.prototype.setSlotsSymbolList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.schema.SlotsGameSymbolModel=} opt_value
 * @param {number=} opt_index
 * @return {!proto.schema.SlotsGameSymbolModel}
 */
proto.schema.SlotsGameModel.prototype.addSlotsSymbol = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.schema.SlotsGameSymbolModel, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.clearSlotsSymbolList = function() {
  return this.setSlotsSymbolList([]);
};


/**
 * repeated double gold_coins_bet_values = 2;
 * @return {!Array<number>}
 */
proto.schema.SlotsGameModel.prototype.getGoldCoinsBetValuesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.setGoldCoinsBetValuesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.addGoldCoinsBetValues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.clearGoldCoinsBetValuesList = function() {
  return this.setGoldCoinsBetValuesList([]);
};


/**
 * repeated double sweep_coins_bet_values = 3;
 * @return {!Array<number>}
 */
proto.schema.SlotsGameModel.prototype.getSweepCoinsBetValuesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.setSweepCoinsBetValuesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.addSweepCoinsBetValues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.clearSweepCoinsBetValuesList = function() {
  return this.setSweepCoinsBetValuesList([]);
};


/**
 * repeated int32 row_counts = 4;
 * @return {!Array<number>}
 */
proto.schema.SlotsGameModel.prototype.getRowCountsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.setRowCountsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.addRowCounts = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.clearRowCountsList = function() {
  return this.setRowCountsList([]);
};


/**
 * repeated ScatterPrizeModel scatter_prizes = 5;
 * @return {!Array<!proto.schema.ScatterPrizeModel>}
 */
proto.schema.SlotsGameModel.prototype.getScatterPrizesList = function() {
  return /** @type{!Array<!proto.schema.ScatterPrizeModel>} */ (
    jspb.Message.getRepeatedWrapperField(this, slotsgames_scatter_prize_pb.ScatterPrizeModel, 5));
};


/**
 * @param {!Array<!proto.schema.ScatterPrizeModel>} value
 * @return {!proto.schema.SlotsGameModel} returns this
*/
proto.schema.SlotsGameModel.prototype.setScatterPrizesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.schema.ScatterPrizeModel=} opt_value
 * @param {number=} opt_index
 * @return {!proto.schema.ScatterPrizeModel}
 */
proto.schema.SlotsGameModel.prototype.addScatterPrizes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.schema.ScatterPrizeModel, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.clearScatterPrizesList = function() {
  return this.setScatterPrizesList([]);
};


/**
 * optional PaylineSlotsGameModel payline_slots_game = 6;
 * @return {?proto.schema.PaylineSlotsGameModel}
 */
proto.schema.SlotsGameModel.prototype.getPaylineSlotsGame = function() {
  return /** @type{?proto.schema.PaylineSlotsGameModel} */ (
    jspb.Message.getWrapperField(this, proto.schema.PaylineSlotsGameModel, 6));
};


/**
 * @param {?proto.schema.PaylineSlotsGameModel|undefined} value
 * @return {!proto.schema.SlotsGameModel} returns this
*/
proto.schema.SlotsGameModel.prototype.setPaylineSlotsGame = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.schema.SlotsGameModel.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.clearPaylineSlotsGame = function() {
  return this.setPaylineSlotsGame(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schema.SlotsGameModel.prototype.hasPaylineSlotsGame = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional WaySlotsGameModel way_slots_game = 7;
 * @return {?proto.schema.WaySlotsGameModel}
 */
proto.schema.SlotsGameModel.prototype.getWaySlotsGame = function() {
  return /** @type{?proto.schema.WaySlotsGameModel} */ (
    jspb.Message.getWrapperField(this, proto.schema.WaySlotsGameModel, 7));
};


/**
 * @param {?proto.schema.WaySlotsGameModel|undefined} value
 * @return {!proto.schema.SlotsGameModel} returns this
*/
proto.schema.SlotsGameModel.prototype.setWaySlotsGame = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.schema.SlotsGameModel.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schema.SlotsGameModel} returns this
 */
proto.schema.SlotsGameModel.prototype.clearWaySlotsGame = function() {
  return this.setWaySlotsGame(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schema.SlotsGameModel.prototype.hasWaySlotsGame = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.schema.SlotsGameSymbolModel.repeatedFields_ = [8];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.schema.SlotsGameSymbolModel.oneofGroups_ = [[9,10]];

/**
 * @enum {number}
 */
proto.schema.SlotsGameSymbolModel.SymbolCase = {
  SYMBOL_NOT_SET: 0,
  ACCUMULATE_MULTIPLIER_SLOTS_GAME_SYMBOL: 9,
  ASYMMETRIC_REELS_SLOTS_GAME_SYMBOL: 10
};

/**
 * @return {proto.schema.SlotsGameSymbolModel.SymbolCase}
 */
proto.schema.SlotsGameSymbolModel.prototype.getSymbolCase = function() {
  return /** @type {proto.schema.SlotsGameSymbolModel.SymbolCase} */(jspb.Message.computeOneofCase(this, proto.schema.SlotsGameSymbolModel.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schema.SlotsGameSymbolModel.prototype.toObject = function(opt_includeInstance) {
  return proto.schema.SlotsGameSymbolModel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schema.SlotsGameSymbolModel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.SlotsGameSymbolModel.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    minimumPaylineToAppear: jspb.Message.getFieldWithDefault(msg, 3, 0),
    chanceRatio: jspb.Message.getFieldWithDefault(msg, 4, 0),
    isWild: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    isJackpot: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    isScatter: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    symbolValuesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 8)) == null ? undefined : f,
    accumulateMultiplierSlotsGameSymbol: (f = msg.getAccumulateMultiplierSlotsGameSymbol()) && slotsgames_accumulate_multiplier_slots_game_pb.AccumulateMultiplierSlotsGameSymbolModel.toObject(includeInstance, f),
    asymmetricReelsSlotsGameSymbol: (f = msg.getAsymmetricReelsSlotsGameSymbol()) && slotsgames_asymmetric_reels_slots_game_pb.AsymmetricReelsSlotsGameSymbolModel.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schema.SlotsGameSymbolModel}
 */
proto.schema.SlotsGameSymbolModel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schema.SlotsGameSymbolModel;
  return proto.schema.SlotsGameSymbolModel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schema.SlotsGameSymbolModel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schema.SlotsGameSymbolModel}
 */
proto.schema.SlotsGameSymbolModel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMinimumPaylineToAppear(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChanceRatio(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsWild(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsJackpot(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsScatter(value);
      break;
    case 8:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSymbolValues(values[i]);
      }
      break;
    case 9:
      var value = new slotsgames_accumulate_multiplier_slots_game_pb.AccumulateMultiplierSlotsGameSymbolModel;
      reader.readMessage(value,slotsgames_accumulate_multiplier_slots_game_pb.AccumulateMultiplierSlotsGameSymbolModel.deserializeBinaryFromReader);
      msg.setAccumulateMultiplierSlotsGameSymbol(value);
      break;
    case 10:
      var value = new slotsgames_asymmetric_reels_slots_game_pb.AsymmetricReelsSlotsGameSymbolModel;
      reader.readMessage(value,slotsgames_asymmetric_reels_slots_game_pb.AsymmetricReelsSlotsGameSymbolModel.deserializeBinaryFromReader);
      msg.setAsymmetricReelsSlotsGameSymbol(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schema.SlotsGameSymbolModel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schema.SlotsGameSymbolModel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schema.SlotsGameSymbolModel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.SlotsGameSymbolModel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMinimumPaylineToAppear();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getChanceRatio();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getIsWild();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getIsJackpot();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getIsScatter();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getSymbolValuesList();
  if (f.length > 0) {
    writer.writePackedDouble(
      8,
      f
    );
  }
  f = message.getAccumulateMultiplierSlotsGameSymbol();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      slotsgames_accumulate_multiplier_slots_game_pb.AccumulateMultiplierSlotsGameSymbolModel.serializeBinaryToWriter
    );
  }
  f = message.getAsymmetricReelsSlotsGameSymbol();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      slotsgames_asymmetric_reels_slots_game_pb.AsymmetricReelsSlotsGameSymbolModel.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.schema.SlotsGameSymbolModel.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.schema.SlotsGameSymbolModel.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 minimum_payline_to_appear = 3;
 * @return {number}
 */
proto.schema.SlotsGameSymbolModel.prototype.getMinimumPaylineToAppear = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.setMinimumPaylineToAppear = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 chance_ratio = 4;
 * @return {number}
 */
proto.schema.SlotsGameSymbolModel.prototype.getChanceRatio = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.setChanceRatio = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bool is_wild = 5;
 * @return {boolean}
 */
proto.schema.SlotsGameSymbolModel.prototype.getIsWild = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.setIsWild = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool is_jackpot = 6;
 * @return {boolean}
 */
proto.schema.SlotsGameSymbolModel.prototype.getIsJackpot = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.setIsJackpot = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool is_scatter = 7;
 * @return {boolean}
 */
proto.schema.SlotsGameSymbolModel.prototype.getIsScatter = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.setIsScatter = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * repeated double symbol_values = 8;
 * @return {!Array<number>}
 */
proto.schema.SlotsGameSymbolModel.prototype.getSymbolValuesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 8));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.setSymbolValuesList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.addSymbolValues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.clearSymbolValuesList = function() {
  return this.setSymbolValuesList([]);
};


/**
 * optional AccumulateMultiplierSlotsGameSymbolModel accumulate_multiplier_slots_game_symbol = 9;
 * @return {?proto.schema.AccumulateMultiplierSlotsGameSymbolModel}
 */
proto.schema.SlotsGameSymbolModel.prototype.getAccumulateMultiplierSlotsGameSymbol = function() {
  return /** @type{?proto.schema.AccumulateMultiplierSlotsGameSymbolModel} */ (
    jspb.Message.getWrapperField(this, slotsgames_accumulate_multiplier_slots_game_pb.AccumulateMultiplierSlotsGameSymbolModel, 9));
};


/**
 * @param {?proto.schema.AccumulateMultiplierSlotsGameSymbolModel|undefined} value
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
*/
proto.schema.SlotsGameSymbolModel.prototype.setAccumulateMultiplierSlotsGameSymbol = function(value) {
  return jspb.Message.setOneofWrapperField(this, 9, proto.schema.SlotsGameSymbolModel.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.clearAccumulateMultiplierSlotsGameSymbol = function() {
  return this.setAccumulateMultiplierSlotsGameSymbol(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schema.SlotsGameSymbolModel.prototype.hasAccumulateMultiplierSlotsGameSymbol = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional AsymmetricReelsSlotsGameSymbolModel asymmetric_reels_slots_game_symbol = 10;
 * @return {?proto.schema.AsymmetricReelsSlotsGameSymbolModel}
 */
proto.schema.SlotsGameSymbolModel.prototype.getAsymmetricReelsSlotsGameSymbol = function() {
  return /** @type{?proto.schema.AsymmetricReelsSlotsGameSymbolModel} */ (
    jspb.Message.getWrapperField(this, slotsgames_asymmetric_reels_slots_game_pb.AsymmetricReelsSlotsGameSymbolModel, 10));
};


/**
 * @param {?proto.schema.AsymmetricReelsSlotsGameSymbolModel|undefined} value
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
*/
proto.schema.SlotsGameSymbolModel.prototype.setAsymmetricReelsSlotsGameSymbol = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.schema.SlotsGameSymbolModel.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schema.SlotsGameSymbolModel} returns this
 */
proto.schema.SlotsGameSymbolModel.prototype.clearAsymmetricReelsSlotsGameSymbol = function() {
  return this.setAsymmetricReelsSlotsGameSymbol(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schema.SlotsGameSymbolModel.prototype.hasAsymmetricReelsSlotsGameSymbol = function() {
  return jspb.Message.getField(this, 10) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.schema.PaylineModel.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schema.PaylineModel.prototype.toObject = function(opt_includeInstance) {
  return proto.schema.PaylineModel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schema.PaylineModel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.PaylineModel.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    rowIndexList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schema.PaylineModel}
 */
proto.schema.PaylineModel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schema.PaylineModel;
  return proto.schema.PaylineModel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schema.PaylineModel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schema.PaylineModel}
 */
proto.schema.PaylineModel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRowIndex(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schema.PaylineModel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schema.PaylineModel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schema.PaylineModel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.PaylineModel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getRowIndexList();
  if (f.length > 0) {
    writer.writePackedInt32(
      2,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.schema.PaylineModel.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.schema.PaylineModel} returns this
 */
proto.schema.PaylineModel.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated int32 row_index = 2;
 * @return {!Array<number>}
 */
proto.schema.PaylineModel.prototype.getRowIndexList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.schema.PaylineModel} returns this
 */
proto.schema.PaylineModel.prototype.setRowIndexList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.schema.PaylineModel} returns this
 */
proto.schema.PaylineModel.prototype.addRowIndex = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.PaylineModel} returns this
 */
proto.schema.PaylineModel.prototype.clearRowIndexList = function() {
  return this.setRowIndexList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.schema.PaylineSlotsGameModel.repeatedFields_ = [1];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.schema.PaylineSlotsGameModel.oneofGroups_ = [[2]];

/**
 * @enum {number}
 */
proto.schema.PaylineSlotsGameModel.GameCase = {
  GAME_NOT_SET: 0,
  ASYMMETRIC_REELS_SLOTS_GAME: 2
};

/**
 * @return {proto.schema.PaylineSlotsGameModel.GameCase}
 */
proto.schema.PaylineSlotsGameModel.prototype.getGameCase = function() {
  return /** @type {proto.schema.PaylineSlotsGameModel.GameCase} */(jspb.Message.computeOneofCase(this, proto.schema.PaylineSlotsGameModel.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schema.PaylineSlotsGameModel.prototype.toObject = function(opt_includeInstance) {
  return proto.schema.PaylineSlotsGameModel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schema.PaylineSlotsGameModel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.PaylineSlotsGameModel.toObject = function(includeInstance, msg) {
  var f, obj = {
    paylinesList: jspb.Message.toObjectList(msg.getPaylinesList(),
    proto.schema.PaylineModel.toObject, includeInstance),
    asymmetricReelsSlotsGame: (f = msg.getAsymmetricReelsSlotsGame()) && slotsgames_asymmetric_reels_slots_game_pb.AsymmetricReelsSlotsGameModel.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schema.PaylineSlotsGameModel}
 */
proto.schema.PaylineSlotsGameModel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schema.PaylineSlotsGameModel;
  return proto.schema.PaylineSlotsGameModel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schema.PaylineSlotsGameModel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schema.PaylineSlotsGameModel}
 */
proto.schema.PaylineSlotsGameModel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.schema.PaylineModel;
      reader.readMessage(value,proto.schema.PaylineModel.deserializeBinaryFromReader);
      msg.addPaylines(value);
      break;
    case 2:
      var value = new slotsgames_asymmetric_reels_slots_game_pb.AsymmetricReelsSlotsGameModel;
      reader.readMessage(value,slotsgames_asymmetric_reels_slots_game_pb.AsymmetricReelsSlotsGameModel.deserializeBinaryFromReader);
      msg.setAsymmetricReelsSlotsGame(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schema.PaylineSlotsGameModel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schema.PaylineSlotsGameModel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schema.PaylineSlotsGameModel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.PaylineSlotsGameModel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPaylinesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.schema.PaylineModel.serializeBinaryToWriter
    );
  }
  f = message.getAsymmetricReelsSlotsGame();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      slotsgames_asymmetric_reels_slots_game_pb.AsymmetricReelsSlotsGameModel.serializeBinaryToWriter
    );
  }
};


/**
 * repeated PaylineModel paylines = 1;
 * @return {!Array<!proto.schema.PaylineModel>}
 */
proto.schema.PaylineSlotsGameModel.prototype.getPaylinesList = function() {
  return /** @type{!Array<!proto.schema.PaylineModel>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.schema.PaylineModel, 1));
};


/**
 * @param {!Array<!proto.schema.PaylineModel>} value
 * @return {!proto.schema.PaylineSlotsGameModel} returns this
*/
proto.schema.PaylineSlotsGameModel.prototype.setPaylinesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.schema.PaylineModel=} opt_value
 * @param {number=} opt_index
 * @return {!proto.schema.PaylineModel}
 */
proto.schema.PaylineSlotsGameModel.prototype.addPaylines = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.schema.PaylineModel, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.schema.PaylineSlotsGameModel} returns this
 */
proto.schema.PaylineSlotsGameModel.prototype.clearPaylinesList = function() {
  return this.setPaylinesList([]);
};


/**
 * optional AsymmetricReelsSlotsGameModel asymmetric_reels_slots_game = 2;
 * @return {?proto.schema.AsymmetricReelsSlotsGameModel}
 */
proto.schema.PaylineSlotsGameModel.prototype.getAsymmetricReelsSlotsGame = function() {
  return /** @type{?proto.schema.AsymmetricReelsSlotsGameModel} */ (
    jspb.Message.getWrapperField(this, slotsgames_asymmetric_reels_slots_game_pb.AsymmetricReelsSlotsGameModel, 2));
};


/**
 * @param {?proto.schema.AsymmetricReelsSlotsGameModel|undefined} value
 * @return {!proto.schema.PaylineSlotsGameModel} returns this
*/
proto.schema.PaylineSlotsGameModel.prototype.setAsymmetricReelsSlotsGame = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.schema.PaylineSlotsGameModel.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schema.PaylineSlotsGameModel} returns this
 */
proto.schema.PaylineSlotsGameModel.prototype.clearAsymmetricReelsSlotsGame = function() {
  return this.setAsymmetricReelsSlotsGame(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schema.PaylineSlotsGameModel.prototype.hasAsymmetricReelsSlotsGame = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.schema.WaySlotsGameModel.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.schema.WaySlotsGameModel.GameCase = {
  GAME_NOT_SET: 0,
  ACCUMULATE_MULTIPLIER_SLOTS_GAME: 1
};

/**
 * @return {proto.schema.WaySlotsGameModel.GameCase}
 */
proto.schema.WaySlotsGameModel.prototype.getGameCase = function() {
  return /** @type {proto.schema.WaySlotsGameModel.GameCase} */(jspb.Message.computeOneofCase(this, proto.schema.WaySlotsGameModel.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.schema.WaySlotsGameModel.prototype.toObject = function(opt_includeInstance) {
  return proto.schema.WaySlotsGameModel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.schema.WaySlotsGameModel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.WaySlotsGameModel.toObject = function(includeInstance, msg) {
  var f, obj = {
    accumulateMultiplierSlotsGame: (f = msg.getAccumulateMultiplierSlotsGame()) && slotsgames_accumulate_multiplier_slots_game_pb.AccumulateMultiplierSlotsGameModel.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.schema.WaySlotsGameModel}
 */
proto.schema.WaySlotsGameModel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.schema.WaySlotsGameModel;
  return proto.schema.WaySlotsGameModel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.schema.WaySlotsGameModel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.schema.WaySlotsGameModel}
 */
proto.schema.WaySlotsGameModel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new slotsgames_accumulate_multiplier_slots_game_pb.AccumulateMultiplierSlotsGameModel;
      reader.readMessage(value,slotsgames_accumulate_multiplier_slots_game_pb.AccumulateMultiplierSlotsGameModel.deserializeBinaryFromReader);
      msg.setAccumulateMultiplierSlotsGame(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.schema.WaySlotsGameModel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.schema.WaySlotsGameModel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.schema.WaySlotsGameModel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.schema.WaySlotsGameModel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccumulateMultiplierSlotsGame();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      slotsgames_accumulate_multiplier_slots_game_pb.AccumulateMultiplierSlotsGameModel.serializeBinaryToWriter
    );
  }
};


/**
 * optional AccumulateMultiplierSlotsGameModel accumulate_multiplier_slots_game = 1;
 * @return {?proto.schema.AccumulateMultiplierSlotsGameModel}
 */
proto.schema.WaySlotsGameModel.prototype.getAccumulateMultiplierSlotsGame = function() {
  return /** @type{?proto.schema.AccumulateMultiplierSlotsGameModel} */ (
    jspb.Message.getWrapperField(this, slotsgames_accumulate_multiplier_slots_game_pb.AccumulateMultiplierSlotsGameModel, 1));
};


/**
 * @param {?proto.schema.AccumulateMultiplierSlotsGameModel|undefined} value
 * @return {!proto.schema.WaySlotsGameModel} returns this
*/
proto.schema.WaySlotsGameModel.prototype.setAccumulateMultiplierSlotsGame = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.schema.WaySlotsGameModel.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.schema.WaySlotsGameModel} returns this
 */
proto.schema.WaySlotsGameModel.prototype.clearAccumulateMultiplierSlotsGame = function() {
  return this.setAccumulateMultiplierSlotsGame(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.schema.WaySlotsGameModel.prototype.hasAccumulateMultiplierSlotsGame = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.schema);
